/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProvisaoRouteImport } from './routes/provisao'
import { Route as PrincipalRouteImport } from './routes/principal'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as BaseRouteImport } from './routes/base'
import { Route as AnexosRouteImport } from './routes/anexos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvisaoIndexRouteImport } from './routes/provisao.index'
import { Route as ProvisaoBaseRouteImport } from './routes/provisao.base'

const ProvisaoRoute = ProvisaoRouteImport.update({
  id: '/provisao',
  path: '/provisao',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalRoute = PrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRoute = BaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRouteImport,
} as any)
const AnexosRoute = AnexosRouteImport.update({
  id: '/anexos',
  path: '/anexos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisaoIndexRoute = ProvisaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvisaoRoute,
} as any)
const ProvisaoBaseRoute = ProvisaoBaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => ProvisaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anexos': typeof AnexosRoute
  '/base': typeof BaseRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/principal': typeof PrincipalRoute
  '/provisao': typeof ProvisaoRouteWithChildren
  '/provisao/base': typeof ProvisaoBaseRoute
  '/provisao/': typeof ProvisaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anexos': typeof AnexosRoute
  '/base': typeof BaseRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/principal': typeof PrincipalRoute
  '/provisao/base': typeof ProvisaoBaseRoute
  '/provisao': typeof ProvisaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anexos': typeof AnexosRoute
  '/base': typeof BaseRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/principal': typeof PrincipalRoute
  '/provisao': typeof ProvisaoRouteWithChildren
  '/provisao/base': typeof ProvisaoBaseRoute
  '/provisao/': typeof ProvisaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anexos'
    | '/base'
    | '/conciliacao'
    | '/principal'
    | '/provisao'
    | '/provisao/base'
    | '/provisao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anexos'
    | '/base'
    | '/conciliacao'
    | '/principal'
    | '/provisao/base'
    | '/provisao'
  id:
    | '__root__'
    | '/'
    | '/anexos'
    | '/base'
    | '/conciliacao'
    | '/principal'
    | '/provisao'
    | '/provisao/base'
    | '/provisao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnexosRoute: typeof AnexosRoute
  BaseRoute: typeof BaseRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  PrincipalRoute: typeof PrincipalRoute
  ProvisaoRoute: typeof ProvisaoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provisao': {
      id: '/provisao'
      path: '/provisao'
      fullPath: '/provisao'
      preLoaderRoute: typeof ProvisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal': {
      id: '/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof PrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anexos': {
      id: '/anexos'
      path: '/anexos'
      fullPath: '/anexos'
      preLoaderRoute: typeof AnexosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisao/': {
      id: '/provisao/'
      path: '/'
      fullPath: '/provisao/'
      preLoaderRoute: typeof ProvisaoIndexRouteImport
      parentRoute: typeof ProvisaoRoute
    }
    '/provisao/base': {
      id: '/provisao/base'
      path: '/base'
      fullPath: '/provisao/base'
      preLoaderRoute: typeof ProvisaoBaseRouteImport
      parentRoute: typeof ProvisaoRoute
    }
  }
}

interface ProvisaoRouteChildren {
  ProvisaoBaseRoute: typeof ProvisaoBaseRoute
  ProvisaoIndexRoute: typeof ProvisaoIndexRoute
}

const ProvisaoRouteChildren: ProvisaoRouteChildren = {
  ProvisaoBaseRoute: ProvisaoBaseRoute,
  ProvisaoIndexRoute: ProvisaoIndexRoute,
}

const ProvisaoRouteWithChildren = ProvisaoRoute._addFileChildren(
  ProvisaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnexosRoute: AnexosRoute,
  BaseRoute: BaseRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  PrincipalRoute: PrincipalRoute,
  ProvisaoRoute: ProvisaoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
